[build]
  base    = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  python_version = "3.11"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api"
  status = 200