[build]
  base    = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = ["backend/**"]  # bundle your old backend code with each function

# Frontend SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# API → Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
