[build]
  base    = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# The function folder is netlify/functions/api (with main.py),
# so configure its runtime explicitly:
[functions."api"]
  runtime = "python3.11"
  included_files = [
    "netlify/functions/api/backend/**"
  ]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api"
  status = 200